name: music_prototype
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  swipable_stack: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  sqflite: ^2.2.6
  flutter_riverpod: ^2.3.2
  http: ^0.13.5
  music_kit: ^1.1.0
  async: ^2.10.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/
